import type { MetricKey, Source } from '../types/rumina-bi';
export const BI_METRICS: Record<MetricKey,{label:string;unit:string;sources:Source[];note?:string}>={
  activeAnimals:{label:'Animais ativos',unit:'',sources:['animaisativos'],note:'Rebanho atual'},
  totalAnimals:{label:'Animais cadastrados',unit:'',sources:['animaistotais'],note:'Histórico total'},
  averageMilk:{label:'Leite por controle',unit:'L',sources:['controleleiteiro'],note:'Média por medição'},
  milkMeasurements:{label:'Controles de leite',unit:'',sources:['controleleiteiro']},
  averageCcs:{label:'CCS média',unit:'',sources:['analiseleite'],note:'Unidade da origem'},
  averageFat:{label:'Gordura',unit:'%',sources:['analiseleite']},
  averageProtein:{label:'Proteína',unit:'%',sources:['analiseleite']},
  tankAnalyses:{label:'Análises de tanque',unit:'',sources:['analisetanque']},
  averageTankCbt:{label:'CBT do tanque',unit:'',sources:['analisetanque'],note:'Média das análises'},
  averageTankCcs:{label:'CCS do tanque',unit:'',sources:['analisetanque'],note:'Média das análises'},
  averageTankFat:{label:'Gordura do tanque',unit:'%',sources:['analisetanque']},
  averageTankProtein:{label:'Proteína do tanque',unit:'%',sources:['analisetanque']},
  averageTankUrea:{label:'Ureia do tanque',unit:'',sources:['analisetanque']},
  averageTankSolids:{label:'Extrato total',unit:'%',sources:['analisetanque']},
  averageTankNonfatSolids:{label:'Extrato desengordurado',unit:'%',sources:['analisetanque']},
  milkProductionEntries:{label:'Lançamentos de produção',unit:'',sources:['producaoleite']},
  averageLactatingCows:{label:'Vacas na produção',unit:'',sources:['producaoleite'],note:'Média dos lançamentos'},
  milkToClient:{label:'Leite para clientes',unit:'L',sources:['producaoleite']},
  milkToEmployees:{label:'Leite para funcionários',unit:'L',sources:['producaoleite']},
  milkToRearing:{label:'Leite para recria',unit:'L',sources:['producaoleite']},
  milkOther:{label:'Outros destinos do leite',unit:'L',sources:['producaoleite']},
  inseminations:{label:'Inseminações',unit:'',sources:['inseminacoes']},
  attempts:{label:'Tentativas reprodutivas',unit:'',sources:['tentativas']},
  coverages:{label:'Coberturas',unit:'',sources:['coberturas']},
  diagnoses:{label:'Diagnósticos reprodutivos',unit:'',sources:['diagnosticos']},
  embryoTransfers:{label:'Transferências de embrião',unit:'',sources:['transferenciaembriao']},
  pregnanciesConfirmed:{label:'Prenhezes confirmadas',unit:'',sources:['inseminacoes']},
  pregnanciesEvaluated:{label:'Resultados registrados',unit:'',sources:['inseminacoes']},
  pregnancyRate:{label:'Prenhez confirmada',unit:'%',sources:['inseminacoes'],note:'Entre IAs com resultado'},
  births:{label:'Partos',unit:'',sources:['partos'],note:'No período'},
  birthRecords:{label:'Nascimentos registrados',unit:'',sources:['nascimentos']},
  calves:{label:'Crias registradas',unit:'',sources:['partos']},
  averageCalvesPerBirth:{label:'Crias por parto',unit:'',sources:['partos'],note:'Média do período'},
  abortions:{label:'Abortos',unit:'',sources:['abortos']},
  mastitisCases:{label:'Casos de mastite',unit:'',sources:['mastite']},
  diseases:{label:'Ocorrências de doenças',unit:'',sources:['doencas']},
  applications:{label:'Aplicações de produtos',unit:'',sources:['aplicacaoproduto']},
  measurements:{label:'Medidas corporais',unit:'',sources:['medidas']},
  averageWeight:{label:'Peso médio',unit:'kg',sources:['pesagemcorporal'],note:'Média das pesagens'},
  averageGmd:{label:'Ganho médio diário',unit:'kg/dia',sources:['pesagemcorporal']},
  averageGpd:{label:'Ganho no período',unit:'kg',sources:['pesagemcorporal']},
  weighings:{label:'Pesagens',unit:'',sources:['pesagemcorporal']},
  weanings:{label:'Desmamas',unit:'',sources:['desmamas']},
  exits:{label:'Baixas de animais',unit:'',sources:['baixas']},
  heats:{label:'Cios não inseminados',unit:'',sources:['ciosnaoinseminados']},
  dryings:{label:'Secagens',unit:'',sources:['secagens']},
  averageDryingDel:{label:'DEL na secagem',unit:'dias',sources:['secagens'],note:'Média das secagens'},
  averageLactationProduction:{label:'Produção por lactação',unit:'L',sources:['secagens'],note:'Média encerrada'},
  averageAdjusted305:{label:'Produção ajustada 305 dias',unit:'L',sources:['secagens'],note:'Média encerrada'},
  revenue:{label:'Receitas',unit:'R$',sources:['receitas'],note:'Valores apropriados'}, revenueEntries:{label:'Lançamentos de receita',unit:'',sources:['receitas']}, averageRevenue:{label:'Receita média',unit:'R$',sources:['receitas']},
  expense:{label:'Despesas',unit:'R$',sources:['despesas'],note:'Valores apropriados'}, expenseEntries:{label:'Lançamentos de despesa',unit:'',sources:['despesas']}, averageExpense:{label:'Despesa média',unit:'R$',sources:['despesas']},
  balance:{label:'Saldo do período',unit:'R$',sources:['receitas','despesas'],note:'Receitas menos despesas'}
};
